server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mal
    username: postgres
    password: admin
  jpa:
    hibernate:
      #WARNING: do not touch, will delete whole database
      ddl-auto: update #zmeneno z create-drop na GitHub, generuje .jar, ktery se uz pouziva