server:
  port: 8080
app:
  name: MalFetcher
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mal
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop